# Generated by Django 5.1.7 on 2025-03-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fertilizer_Name', models.CharField(max_length=100)),
                ('Best_Buyer_Link', models.URLField(max_length=100)),
                ('Description', models.TextField(max_length=200)),
            ],
        ),
    ]
