# Generated by Django 5.1.7 on 2025-03-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('moisture', models.FloatField()),
                ('soil_type', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('predicted_fertilizer', models.CharField(max_length=100)),
                ('nitrogen', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('phosphorous', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
